### ISSUE TITLE
Racket file extension

### ISSUE THREAD

**Issue by activekjw** [philwhln/stackato-racket-example#1]
The usual Racket file extension is .rkt and your files use .mkt.  I've Googled about for precedent and it seems the only precedent set is in the Heroku Racket buildpack.  I checked the docs for raco and all of the examples in its docs use .rkt.  Would it be worth changing the extension to match the common case?

**Comment by philwhln** [comment]
I wondered about that too. Happy to change it. The Heroku buildpack actually refers to it as something else again in the README.md

**Comment by edwardearnest** [comment]
Found this while googling myself.  Best citation I could find: http://docs.racket-lang.org/drracket/drracket-files.html

> The standard file extension for a Racket program file is ".rkt". The extensions ".ss", ".scm", and ".sch" are also historically popular.
